package io.github.hideyukimori.nenepixel.core.pixelengine.measurement

internal object P2CandidateMeasurementReportSchema {
    fun headerRow(): String = csvRow(*columns.toTypedArray())

    fun rowByColumn(vararg values: Pair<String, Any>): String {
        val valuesByColumn = values.toMap()
        check(valuesByColumn.keys.all(columns::contains)) { "Unknown candidate report column." }
        return csvRow(*columns.map { column -> valuesByColumn[column] ?: "" }.toTypedArray())
    }

    private fun csvRow(vararg values: Any): String =
        values.joinToString(",") { value -> "\"${value.toString().replace("\"", "\"\"")}\"" }

    private val columns: List<String> =
        listOf(
            "record_type",
            "name",
            "value",
            "status",
            "canvas_width",
            "canvas_height",
            "pixel_count",
            "path_positions",
            "unique_path_positions",
            "duplicate_path_positions",
            "unchanged_unique_positions",
            "change_count",
            "history_entries",
            "total_retained_changes",
            "warmup",
            "samples",
            "sample_index",
            "latency_ns",
            "allocated_bytes",
            "latency_median_ns",
            "latency_p95_ns",
            "latency_p99_ns",
            "allocated_median_bytes",
            "allocated_p95_bytes",
            "allocated_p99_bytes",
            "boundary",
            "configuration_id",
            "snapshot_candidate_id",
            "patch_candidate_id",
            "inverse_policy",
            "operation_kind",
            "operation_boundary",
            "content_kind",
            "path_kind",
            "color_cardinality",
            "tile_edge",
            "touched_units",
            "copied_units",
            "shared_units",
            "primitive_payload_bytes",
            "reference_slots",
            "copied_primitive_bytes",
            "copied_reference_slots",
            "forward_patch_primitive_bytes",
            "forward_patch_reference_slots",
            "forward_patch_object_records",
            "forward_patch_primitive_backing_arrays",
            "inverse_additional_primitive_bytes",
            "inverse_additional_reference_slots",
            "inverse_additional_object_records",
            "inverse_additional_primitive_backing_arrays",
            "shared_patch_primitive_bytes",
            "shared_patch_reference_slots",
            "shared_patch_object_records",
            "shared_patch_primitive_backing_arrays",
            "retained_patch_union_primitive_bytes",
            "retained_patch_union_reference_slots",
            "retained_patch_union_object_records",
            "retained_patch_union_primitive_backing_arrays",
            "retained_snapshot_primitive_bytes",
            "retained_snapshot_reference_slots",
            "retained_forward_patch_primitive_bytes",
            "retained_forward_patch_reference_slots",
            "retained_forward_patch_object_records",
            "retained_forward_patch_primitive_backing_arrays",
            "retained_inverse_additional_primitive_bytes",
            "retained_inverse_additional_reference_slots",
            "retained_inverse_additional_object_records",
            "retained_inverse_additional_primitive_backing_arrays",
            "retained_shared_patch_primitive_bytes",
            "retained_shared_patch_reference_slots",
            "retained_shared_patch_object_records",
            "retained_shared_patch_primitive_backing_arrays",
            "retained_history_patch_union_primitive_bytes",
            "retained_history_patch_union_reference_slots",
            "retained_history_patch_union_object_records",
            "retained_history_patch_union_primitive_backing_arrays",
            "result_kind",
            "rejection_kind",
            "conflict_position",
            "unaffected_pixel_count",
            "affected_left",
            "affected_top",
            "affected_width",
            "affected_height",
            "expected_lifecycle_before_revision",
            "expected_lifecycle_after_revision",
            "expected_lifecycle_restored_revision",
            "expected_lifecycle_before_pixel_digest_sha256",
            "expected_lifecycle_after_pixel_digest_sha256",
            "expected_lifecycle_restored_pixel_digest_sha256",
            "operation_input_revision",
            "operation_output_revision",
            "operation_input_pixel_digest_sha256",
            "operation_output_pixel_digest_sha256",
            "operation_state_unchanged",
            "unaffected_input_digest_sha256",
            "unaffected_output_digest_sha256",
            "canonical_order_digest_sha256",
            "raw_input_digest_sha256",
            "canonical_change_digest_sha256",
            "forward_patch_digest_sha256",
            "inverse_patch_digest_sha256",
            "retained_entry_change_counts_digest_sha256",
            "retained_history_semantic_digest_sha256",
            "execution_order",
            "input_order",
            "semantic_digest",
            "inverse_digest",
            "correctness_status",
        )
}
