config:
  validation: true
  warningsAsErrors: true
  excludes:
    - "nene-architecture.*"

complexity:
  CognitiveComplexMethod:
    active: true
    allowedComplexity: 10
  LongMethod:
    active: true
    allowedLines: 40
  LongParameterList:
    active: true
    allowedFunctionParameters: 4
    allowedConstructorParameters: 4
    ignoreDefaultParameters: false
    ignoreDataClasses: false
  NestedBlockDepth:
    active: true
    allowedDepth: 3

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable

nene-architecture:
  ForbiddenGenericName:
    active: true
